### ISSUE TITLE
Implement Component Tests

### ISSUE THREAD

**Issue by NazWright** [NazWright/Uwallet#2]
As UWallet continues to grow in consistency and scale, it is imperative to establish a robust testing framework to ensure stability, reliability, and maintainability. Currently, the absence of an automated testing framework exposes the application to inconsistencies and regressions that could impact the user experience and product quality.

## Objective 

The primary objective of this issue is to implement an automated testing suite across the UI portion of the project codebase.

## Acceptance Criteria

- Unit Tests are implemented to test the functionality of the test suite.
- Automated tests are integrated into the Amplify CI/CD Pipeline and execute successfully on code changes. 

##Note

- This is the issue for end to end tests, component tests will be in a separate issue.

## TASKS

- [ ] Create new module for the automation tests and init a new npm project.
- [ ] Install Cypress 
- [ ] Write an example test
- [ ] Edit Amplify build configuration
- [ ] Ensure Cypress test suite runs and passes in Amplify build
